let players=[];
let lastPlayers=[];
let lastResults=[];
let lastSuccessAt=0;
const SNAPSHOT_MAX_FRESH_MS=15*60*1000;
const photo=id=>`https://img.mlbstatic.com/mlb-photos/image/upload/w_640,q_auto:best,f_auto/v1/people/${id}/headshot/67/current`;
const val=(v,f='—')=>v??f,num=v=>Number(v||0),day=v=>String(v||'').slice(0,10);
const formatTime=ts=>ts?new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(ts)):'—';
const names=p=>{const a=String(p?.name||'').split(' ');return {zh:a.shift()||'',en:a.join(' ')}};
function setTrackedPlayers(list){players=Array.isArray(list)?list:[];window.trackedPlayers=players;return players;}
function initials(p){return names(p).en.split(' ').filter(Boolean).map(x=>x[0]).slice(0,2).join('').toUpperCase();}
function image(p,large=false){return `<div class="photo ${large?'photo-large':''}"><img src="${photo(p.id)}" alt="${p.name} 球員照片" loading="lazy" decoding="async" referrerpolicy="no-referrer"><span aria-hidden="true"><b>${initials(p)}</b><small>TAIWAN BASEBALL</small></span></div>`;}
function wireImages(){document.querySelectorAll('.photo img:not([data-wired])').forEach(img=>{img.dataset.wired='1';const fail=()=>img.parentElement.classList.add('fallback');img.addEventListener('error',fail,{once:true});if(img.complete&&!img.naturalWidth)fail();});}
function currentLevel(r){return r?.latest?.level||r?.levels?.find(x=>x.season)?.level||'—';}
function line(p,g){const s=g?.stat||{};return p.group==='pitching'?`${val(s.inningsPitched,'0')} IP · ${val(s.hits,0)} H · ${val(s.earnedRuns,0)} ER · ${val(s.baseOnBalls,0)} BB · ${val(s.strikeOuts,0)} K${s.battersFaced!=null?` · ${s.battersFaced} BF`:''}`:`${val(s.hits,0)}-${val(s.atBats,0)}${s.plateAppearances!=null?` · ${s.plateAppearances} PA`:''} · ${num(s.homeRuns)?`${s.homeRuns} HR · `:''}${num(s.rbi)?`${s.rbi} RBI`:''}`.replace(/ · $/,'');}
function ratio(a,b,digits=2){return a!=null&&b!=null&&num(b)>0?(num(a)/num(b)).toFixed(digits):'—';}
function rate(n,pa){return n!=null&&pa!=null&&num(pa)>0?`${(num(n)/num(pa)*100).toFixed(1)}%`:'—';}
function hitterMetrics(s={}){const doubles=s.doubles,triples=s.triples,hr=s.homeRuns,hasXbh=[doubles,triples,hr].every(x=>x!=null);let iso='—';if(s.slg!=null&&s.avg!=null&&!Number.isNaN(Number(s.slg))&&!Number.isNaN(Number(s.avg)))iso=(Number(s.slg)-Number(s.avg)).toFixed(3).replace(/^0/,'');return [['AVG',s.avg],['OBP',s.obp],['SLG',s.slg],['OPS',s.ops],['HR',hr],['RBI',s.rbi],['H',s.hits],['2B',doubles],['3B',triples],['XBH',hasXbh?num(doubles)+num(triples)+num(hr):null],['BB',s.baseOnBalls],['SO',s.strikeOuts],['BB/K',ratio(s.baseOnBalls,s.strikeOuts)],['BB%',rate(s.baseOnBalls,s.plateAppearances)],['K%',rate(s.strikeOuts,s.plateAppearances)],['ISO',iso]];}
function pitcherMetrics(s={}){return [['ERA',s.era],['WHIP',s.whip],['W-L',s.wins!=null&&s.losses!=null?`${s.wins}-${s.losses}`:null],['IP',s.inningsPitched],['H',s.hits],['ER',s.earnedRuns],['HR',s.homeRuns],['BB',s.baseOnBalls],['SO',s.strikeOuts],['K/9',s.strikeoutsPer9Inn],['BB/9',s.walksPer9Inn],['K/BB',s.strikeoutWalkRatio],['H/9',s.hitsPer9Inn],['HR/9',s.homeRunsPer9]];}
function metricGrid(p,s){const metrics=p.group==='pitching'?pitcherMetrics(s):hitterMetrics(s);return `<div class="metric-grid">${metrics.map(([label,value])=>`<div><span>${label}</span><strong>${val(value)}</strong></div>`).join('')}</div>`;}
function opponent(g){const o=g?.opponent?.name||g?.opponent?.abbreviation||'—';return o.replace(/^(Detroit|Boston|Houston|Arizona|Los Angeles|St. Louis|San Francisco) /,'');}
function result(g){if(g?.isWin===true)return '勝';if(g?.isWin===false)return '敗';return g?.game?.gamePk?'終場':'—';}
function gameRows(p,games=[]){if(!games.length)return '<p class="empty">目前沒有近 5 場比賽資料</p>';const heads=p.group==='pitching'?['日期 / 對手','結果','IP','H','ER','BB','SO']:['日期 / 對手','結果','AB','H','HR','RBI','BB','SO'];return `<div class="game-table"><div class="game-row game-head">${heads.map(x=>`<span>${x}</span>`).join('')}</div>${games.slice(0,5).map(g=>{const s=g.stat||{},d=new Date(`${day(g.date)}T12:00:00Z`),date=`${d.getUTCMonth()+1}/${d.getUTCDate()}`,cells=p.group==='pitching'?[`${date} <b>${opponent(g)}</b>`,result(g),val(s.inningsPitched,0),val(s.hits,0),val(s.earnedRuns,0),val(s.baseOnBalls,0),val(s.strikeOuts,0)]:[`${date} <b>${opponent(g)}</b>`,result(g),val(s.atBats,0),val(s.hits,0),val(s.homeRuns,0),val(s.rbi,0),val(s.baseOnBalls,0),val(s.strikeOuts,0)];return `<div class="game-row">${cells.map(x=>`<span>${x}</span>`).join('')}</div>`}).join('')}</div>`;}
function snapshotFresh(){return lastSuccessAt>0&&Date.now()-lastSuccessAt<=SNAPSHOT_MAX_FRESH_MS;}
function noAppearanceLabel(p){return snapshotFresh()?(p.group==='pitching'?'今日無登板 · MLB 已檢查':'今日未出賽 · MLB 已檢查'):'等待 MLB 更新';}
function summaryRow(p,r){const n=names(p),s=r?.season||{},today=r?.today?`${line(p,r.today)}${r.today.live?' · LIVE':''}`:noAppearanceLabel(p),primary=p.group==='pitching'?s.era:s.avg,secondary=p.group==='pitching'?s.whip:s.ops;return `<a class="summary-row" href="#player-${p.id}" aria-label="查看 ${p.name} 詳細資料"><span class="summary-player"><strong>${n.zh}</strong><small>${n.en}</small></span><span class="summary-club"><b>${currentLevel(r)}</b><small>${p.org||''}</small></span><span class="summary-today">${today}</span><span class="summary-stat"><small>${p.group==='pitching'?'ERA':'AVG'}</small><b>${val(primary)}</b></span><span class="summary-stat"><small>${p.group==='pitching'?'WHIP':'OPS'}</small><b>${val(secondary)}</b></span><i aria-hidden="true">›</i></a>`;}
function summaryGroup(group,results){const hitters=group==='hitting',items=players.map((p,i)=>({p,r:results[i]||{}})).filter(x=>x.p.group===group);return `<section class="summary-group ${group}" aria-labelledby="${group}-title"><header><h3 id="${group}-title">${hitters?'野手':'投手'} <span>${hitters?'HITTERS':'PITCHERS'}</span></h3><div class="column-labels"><span>球員</span><span>球隊 / 層級</span><span>${hitters?'今日戰況':'今日 / 登板'}</span><span>${hitters?'AVG':'ERA'}</span><span>${hitters?'OPS':'WHIP'}</span></div></header>${items.map(({p,r})=>summaryRow(p,r)).join('')}</section>`;}
function detail(p,r={}){const n=names(p),today=Boolean(r.today),status=today?(r.today.live?'LIVE · 已出賽':'已出賽'):noAppearanceLabel(p);return `<article class="player-detail" id="player-${p.id}"><header>${image(p,true)}<div><span class="level">${currentLevel(r)}</span><h3>${n.zh}</h3><b>${n.en}</b><p>${p.org||''} · ${p.role||''}</p></div></header><div class="today-detail"><span>今日賽事</span><strong>${status}</strong><p>${today?line(p,r.today):(snapshotFresh()?'MLB 官方目前未確認出賽':'最後驗證資料保留中；等待 MLB 下一次成功更新')}</p></div><section class="last-five"><div class="subhead"><h4>${p.group==='pitching'?'近 5 次登板':'近 5 場比賽'}</h4><span>LAST 5</span></div>${gameRows(p,r.games||[])}</section><section class="season-stats"><div class="subhead"><h4>本季成績</h4><span>SEASON</span></div>${metricGrid(p,r.season||{})}</section></article>`;}
function updateMetrics(results){const played=results.map((r,i)=>[r,players[i]]).filter(([r])=>r?.today),hits=played.reduce((a,[r,p])=>a+(p.group==='hitting'?num(r.today.stat?.hits):0),0),ks=played.reduce((a,[r,p])=>a+(p.group==='pitching'?num(r.today.stat?.strikeOuts):0),0),hot=played.filter(([r,p])=>p.group==='hitting'?num(r.today.stat?.hits)>1||num(r.today.stat?.homeRuns):num(r.today.stat?.strikeOuts)>=4);document.querySelector('#player-count').textContent=players.length;document.querySelector('#today-count').textContent=played.length;document.querySelector('#highlight-count').textContent=hot.length;document.querySelector('#daily-total').textContent=`${hits} / ${ks}`;}
function paint(results,statusText){const summary=document.querySelector('#player-summary'),details=document.querySelector('#player-details');summary.innerHTML=summaryGroup('hitting',results)+summaryGroup('pitching',results);details.innerHTML=players.map((p,i)=>detail(p,results[i]||{})).join('');updateMetrics(results);wireImages();document.querySelector('#last-update').textContent=statusText;document.dispatchEvent(new CustomEvent('tracker:players-loaded',{detail:players}));}
function loadCanonicalSnapshot(){const snapshot=window.CENTRAL_DASHBOARD_SNAPSHOT;if(!snapshot||!Array.isArray(snapshot.players)||!Array.isArray(snapshot.results)||snapshot.players.length!==snapshot.results.length||!snapshot.players.length)throw new Error('Canonical MLB snapshot unavailable');setTrackedPlayers(snapshot.players);lastPlayers=structuredClone(snapshot.players);lastResults=structuredClone(snapshot.results);lastSuccessAt=Number(snapshot.savedAt)||0;const ageMin=lastSuccessAt?Math.max(0,Math.round((Date.now()-lastSuccessAt)/60000)):null;const status=snapshotFresh()?`VERIFIED · MLB ${formatTime(lastSuccessAt)}${ageMin!=null?` · ${ageMin} min ago`:''}`:`STALE · 最後 MLB 驗證 ${formatTime(lastSuccessAt)}${ageMin!=null?` · ${ageMin} min ago`:''} · 等待下一次官方更新`;paint(lastResults,status);return lastResults;}
window.applyTrackedPlayers=async()=>{document.querySelector('#last-update').textContent='觀察名單已變更 · 等待 canonical MLB snapshot 更新';return lastResults;};
window.refreshCanonicalView=()=>loadCanonicalSnapshot();
document.querySelector('#today-date').textContent=new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',month:'numeric',day:'numeric',weekday:'short'}).format(new Date());
document.querySelector('#refresh-btn').addEventListener('click',()=>{document.querySelector('#last-update').textContent='等待 canonical MLB snapshot / LIVE feed 更新 · 不使用本機快取猜測';});
try{loadCanonicalSnapshot()}catch(error){console.error(error);document.querySelector('#player-summary').innerHTML='<div class="loading">MLB canonical snapshot 暫時不可用；請稍後再試。網站不會用本機舊資料假裝最新。</div>';document.querySelector('#last-update').textContent='WAITING FOR MLB · canonical snapshot unavailable';}
