const players = [
  {id:701678,name:'李灝宇 Hao-Yu Lee',role:'2B',org:'Detroit Tigers',group:'hitting'},
  {id:691907,name:'鄭宗哲 Tsung-Che Cheng',role:'SS',org:'Boston Red Sox',group:'hitting'},
  {id:678906,name:'鄧愷威 Kai-Wei Teng',role:'RHP',org:'Houston Astros',group:'pitching'},
  {id:827734,name:'林維恩 Wei-En Lin',role:'LHP',org:'Athletics',group:'pitching'},
  {id:801179,name:'林昱珉 Yu-Min Lin',role:'LHP',org:'Arizona Diamondbacks',group:'pitching'},
  {id:828667,name:'柯敬賢 Ching-Hsien Ko',role:'OF',org:'Los Angeles Dodgers',group:'hitting'},
  {id:813820,name:'林振瑋 Chen-Wei Lin',role:'RHP',org:'St. Louis Cardinals',group:'pitching'},
  {id:800018,name:'莊陳仲敖 Chen Zhong-Ao Zhuang',role:'RHP',org:'Athletics',group:'pitching'},
  {id:808486,name:'李晨薰 Chen-Hsun Lee',role:'RHP',org:'San Francisco Giants',group:'pitching'}
];
const API='https://statsapi.mlb.com/api/v1';
const LEVELS=[[1,'MLB'],[11,'AAA'],[12,'AA'],[13,'高階 1A'],[14,'1A'],[16,'新人聯盟']];
const photo=id=>`https://img.mlbstatic.com/mlb-photos/image/upload/w_640,q_auto:best,f_auto/v1/people/${id}/headshot/67/current`;
const val=(v,f='—')=>v??f, num=v=>Number(v||0), day=v=>String(v||'').slice(0,10);
const twToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const gameDay=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const names=p=>{const a=p.name.split(' ');return {zh:a.shift(),en:a.join(' ')}};
const gameId=g=>g.game?.gamePk||`${g.date}-${g.level}`;
function gamesSorted(games){const seen=new Set;return games.filter(g=>{const k=gameId(g);if(seen.has(k))return false;seen.add(k);return g.date}).sort((a,b)=>new Date(b.date)-new Date(a.date));}
function initials(p){return names(p).en.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();}
function image(p,large=false){return `<div class="photo ${large?'photo-large':''}"><img src="${photo(p.id)}" alt="${p.name} 球員照片" loading="lazy" decoding="async"><span aria-hidden="true">${initials(p)}</span></div>`;}
function wireImages(){document.querySelectorAll('.photo img:not([data-wired])').forEach(img=>{img.dataset.wired='1';const fail=()=>img.parentElement.classList.add('fallback');img.addEventListener('error',fail,{once:true});if(img.complete&&!img.naturalWidth)fail();});}
function currentLevel(r){return r.latest?.level||r.levels.find(x=>x.season)?.level||'—';}
function line(p,g){const s=g?.stat||{};return p.group==='pitching'?`${val(s.inningsPitched,'0')} IP · ${val(s.hits,0)} H · ${val(s.earnedRuns,0)} ER · ${val(s.baseOnBalls,0)} BB · ${val(s.strikeOuts,0)} K`:`${val(s.hits,0)}-${val(s.atBats,0)} · ${num(s.homeRuns)?`${s.homeRuns} HR · `:''}${num(s.rbi)?`${s.rbi} RBI`:''}`.replace(/ · $/,'');}
function season(p,s={}){return p.group==='pitching'?`ERA ${val(s.era)} / ${val(s.inningsPitched,'0')} IP / ${val(s.strikeOuts,0)} K / ${val(s.whip)} WHIP`:`${val(s.avg)} AVG / ${val(s.homeRuns,0)} HR / ${val(s.rbi,0)} RBI / ${val(s.ops)} OPS`;}
function recentTotals(p,games){const gs=games.slice(0,5), sum=k=>gs.reduce((a,g)=>a+num(g.stat?.[k]),0);if(!gs.length)return '尚無資料';if(p.group==='pitching'){const ip=gs.reduce((a,g)=>a+num(g.stat?.inningsPitched),0),er=sum('earnedRuns'),bb=sum('baseOnBalls'),h=sum('hits');return `${ip?((er*9)/ip).toFixed(2):'0.00'} ERA · ${ip.toFixed(1)} IP · ${sum('strikeOuts')} K · ${ip?((bb+h)/ip).toFixed(2):'0.00'} WHIP`;}
 const ab=sum('atBats'),h=sum('hits'),tb=gs.reduce((a,g)=>a+num(g.stat?.totalBases),0),bb=sum('baseOnBalls'),sf=sum('sacFlies'),hbp=sum('hitByPitch'),avg=ab?(h/ab).toFixed(3).replace(/^0/,''):'.000',obp=(ab+bb+hbp+sf)?(h+bb+hbp)/(ab+bb+hbp+sf):0,slg=ab?tb/ab:0;return `${avg} AVG · ${h} H · ${sum('homeRuns')} HR · ${sum('rbi')} RBI · ${(obp+slg).toFixed(3).replace(/^0/,'')} OPS`;}
function opponent(g){const o=g.opponent?.name||g.opponent?.abbreviation||'—';return o.replace(/^(Detroit|Boston|Houston|Arizona|Los Angeles|St. Louis|San Francisco) /,'');}
function result(g){if(g.isWin===true)return '勝';if(g.isWin===false)return '敗';return g.game?.gamePk?'終場':'—';}
function gameRows(p,games){if(!games.length)return '<p class="empty">目前沒有近 5 場比賽資料</p>';const heads=p.group==='pitching'?['日期 / 對手','結果','IP','H','ER','BB','SO']:['日期 / 對手','結果','AB','H','HR','RBI','BB','SO'];return `<div class="game-table"><div class="game-row game-head">${heads.map(x=>`<span>${x}</span>`).join('')}</div>${games.slice(0,5).map(g=>{const s=g.stat||{},d=new Date(`${day(g.date)}T12:00:00Z`),date=`${d.getUTCMonth()+1}/${d.getUTCDate()}`,cells=p.group==='pitching'?[`${date} <b>${opponent(g)}</b>`,result(g),val(s.inningsPitched,0),val(s.hits,0),val(s.earnedRuns,0),val(s.baseOnBalls,0),val(s.strikeOuts,0)]:[`${date} <b>${opponent(g)}</b>`,result(g),val(s.atBats,0),val(s.hits,0),val(s.homeRuns,0),val(s.rbi,0),val(s.baseOnBalls,0),val(s.strikeOuts,0)];return `<div class="game-row">${cells.map(x=>`<span>${x}</span>`).join('')}</div>`}).join('')}</div>`;}
function summaryRow(p,r){const n=names(p),today=r.today?line(p,r.today):'今日未出賽';return `<a class="summary-row" href="#player-${p.id}"><div class="summary-player">${image(p)}<div><strong>${n.zh}</strong><span>${n.en}</span><small>${p.org} · ${currentLevel(r)}</small></div></div><div data-label="今日">${today}</div><div data-label="近 5 場">${recentTotals(p,r.games)}</div><div data-label="球季">${season(p,r.season)}</div><i aria-hidden="true">›</i></a>`;}
function detail(p,r){const n=names(p),today=Boolean(r.today);return `<article class="player-detail" id="player-${p.id}"><header>${image(p,true)}<div><span class="level">${currentLevel(r)}</span><h3>${n.zh}</h3><b>${n.en}</b><p>${p.org} · ${p.role}</p></div></header><div class="today-detail"><span>今日賽事</span><strong>${today?'已出賽':'今日未出賽'}</strong><p>${today?line(p,r.today):'等待下一場比賽'}</p></div><section class="last-five"><div class="subhead"><h4>近 5 場</h4><span>${p.group==='pitching'?'近 5 次出賽':'最近 5 場比賽'}</span></div>${gameRows(p,r.games)}</section><section class="season-line"><span>本季成績</span><strong>${season(p,r.season)}</strong></section></article>`;}
async function fetchLevel(p,[sportId,level]){const base=`${API}/people/${p.id}/stats?group=${p.group}&season=${new Date().getFullYear()}&sportId=${sportId}`;try{const [a,b]=await Promise.all([fetch(`${base}&stats=season`),fetch(`${base}&stats=gameLog`)]);if(!a.ok||!b.ok)throw Error();const [sj,gj]=await Promise.all([a.json(),b.json()]);return {level,season:sj.stats?.[0]?.splits?.[0]?.stat||null,games:(gj.stats?.[0]?.splits||[]).map(g=>({...g,level}))};}catch{return {level,season:null,games:[]}}}
async function load(p){const levels=await Promise.all(LEVELS.map(l=>fetchLevel(p,l))),games=gamesSorted(levels.flatMap(x=>x.games)),latest=games[0],active=levels.find(x=>x.level===latest?.level)||levels.find(x=>x.season)||{};return {levels,games,latest,today:games.find(g=>day(g.date)===gameDay()),season:active.season||{}};}
function updateMetrics(results){const played=results.map((r,i)=>[r,players[i]]).filter(([r])=>r.today),hits=played.reduce((a,[r,p])=>a+(p.group==='hitting'?num(r.today.stat?.hits):0),0),ks=played.reduce((a,[r,p])=>a+(p.group==='pitching'?num(r.today.stat?.strikeOuts):0),0),hot=played.filter(([r,p])=>p.group==='hitting'?num(r.today.stat?.hits)>1||num(r.today.stat?.homeRuns):num(r.today.stat?.strikeOuts)>=4);document.querySelector('#player-count').textContent=players.length;document.querySelector('#today-count').textContent=played.length;document.querySelector('#highlight-count').textContent=hot.length;document.querySelector('#daily-total').textContent=`${hits} / ${ks}`;}
async function render(){const summary=document.querySelector('#player-summary'),details=document.querySelector('#player-details');summary.innerHTML='<div class="loading">正在讀取 MLB / MiLB 資料…</div>';const results=await Promise.all(players.map(load));summary.innerHTML=players.map((p,i)=>summaryRow(p,results[i])).join('');details.innerHTML=players.map((p,i)=>detail(p,results[i])).join('');updateMetrics(results);wireImages();document.querySelector('#last-update').textContent=`更新 ${new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date())}`;}
document.querySelector('#today-date').textContent=new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',month:'numeric',day:'numeric',weekday:'short'}).format(new Date());
document.querySelector('#refresh-btn').addEventListener('click',async e=>{e.currentTarget.disabled=true;await render();e.currentTarget.disabled=false;});
render();
